language: cpp
dist: xenial
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
          - lcov
          - g++-9
          - libgl1-mesa-dev 
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-9"
      script:
        - eval "${MATRIX_EVAL}"
        - PARENTDIR=$(pwd)
        - mkdir $PARENTDIR/build
        - cd $PARENTDIR/build
        - cmake $PARENTDIR -DCMAKE_CXX_COMPILER=$CXX_COMPILER
        - make

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          update: true

      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"
      script:
        - eval "${MATRIX_EVAL}"
        - PARENTDIR=$(pwd)
        - mkdir $PARENTDIR/build
        - cd $PARENTDIR/build
        - cmake $PARENTDIR -DCMAKE_CXX_COMPILER=$CXX_COMPILER
        - make

    - os: windows
      script:
        - PARENTDIR=$(pwd)
        - mkdir $PARENTDIR/build
        - cd $PARENTDIR/build
        - cmake $PARENTDIR
        - cmake --build . --config Release

after_success:
  - cd $PARENTDIR/build
