trigger:
- master

pr:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.15'
    
  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
    
  - script: |
      sudo xcode-select --switch /Applications/Xcode_11.3.1.app/Contents/Developer
    displayName: 'Select XCode 11.3.1'
    
  - script: |
      mkdir buildmacOS
      cd buildmacOS
      cmake .. -GXcode
    displayName: 'Generate macOS solution'
      
  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'buildmacOS/Gemoni.xcodeproj'
      scheme: 'Gemoni'
      sdk: 'macosx'
      useXcpretty: false
    displayName: 'Build macOS'

- job: win32_x64
  timeoutInMinutes: 20
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'

  - script: |
      mkdir buildWin32_x64
      cd buildWin32_x64
      cmake -G "Visual Studio 16 2019" -A x64 ..
    displayName: 'Generate Win32_x64 solution'
    
  - task: MSBuild@1
    inputs:
      solution: 'buildWin32_x64/Gemoni.sln'
      maximumCpuCount: true
      configuration: 'Release'
    displayName: 'Build WIN32_x64'

- job: Ubuntu_GCC9_JSC
  timeoutInMinutes: 20
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CC: gcc-9
    CXX: g++-9

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
  - script: |
      sudo apt-get update
      sudo apt-get install libgl1-mesa-dev gcc-9 libc++-9-dev libc++abi-9-dev lld-9 ninja-build
    displayName: 'Install packages'
  - script: |
      mkdir build
      cd build
      cmake .. -GNinja -Wno-dev
      ninja
    displayName: 'Build X11'

